# Generated by Django 3.2.16 on 2022-12-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=35)),
                ('department', models.CharField(max_length=50)),
                ('roll', models.IntegerField()),
                ('registration', models.IntegerField()),
            ],
        ),
    ]
